In [28]:
#Normalization Problem

import numpy as np

# Create a random 5x5 array (values between 0 and 1)
X = np.random.random((5, 5))

# Find the mean (average) of all elements in X
mean_X = X.mean()

# Find the standard deviation (how spread out the values are)
standard_dev_X = X.std()

# Apply the normalization formula
# Z = (X - mean) / standard deviation
# This makes the new data have mean ~0 and std ~1
Z = (X - mean_X) / standard_dev_X

# Save the normalized array
np.save("X_normalized.npy", Z)

# Print results
print("Original X: \n", X)                # show the random 5x5 array
print("\nMean:", mean_X)                  # show the mean
print("Standard Deviation:", standard_dev_X)  # show the std
print("\nNormalized X (Z): \n", Z)        # show the normalized array


Original X: 
 [[0.88367179 0.63743591 0.90229599 0.85401074 0.10515495]
 [0.19848388 0.50932351 0.50477814 0.03033448 0.42967097]
 [0.22843475 0.53468238 0.67035367 0.07337867 0.27595949]
 [0.44840374 0.28524976 0.16079708 0.71623336 0.18348819]
 [0.23326322 0.91201841 0.50467096 0.40092487 0.30654384]]

Mean: 0.43958250963019047
Standard Deviation: 0.26605069369325396

Normalized X (Z): 
 [[ 1.66919048  0.74366804  1.73919293  1.55770401 -1.25700692]
 [-0.90621312  0.26213424  0.24504965 -1.53823326 -0.03725434]
 [-0.79363734  0.35745017  0.86739546 -1.37644384 -0.61500692]
 [ 0.03315619 -0.58008776 -1.04786583  1.03984261 -0.96257714]
 [-0.77548863  1.77573641  0.24464681 -0.14530179 -0.50005008]]


In [5]:
#Divisible by 3 Problem

import numpy as np

# Create an array of integers from 1 to 100
numbers = np.arange(1, 101)  

# Square each integer in the array
squares = numbers**2  

# Reshape the squared values into a 10x10 matrix
A = squares.reshape(10, 10)  

# Select only the squared numbers that are multiples of 3
div_by_3 = squares[squares % 3 == 0]  

# Save the divisible-by-3 results into a .npy file
np.save("div_by_3.npy", div_by_3)  

# Display the numbers divisible by 3
print(div_by_3)  

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
